# Generated by Django 6.0.6 on 2026-09-11 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetroalimentacionConstructiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspectos_positivos', models.TextField(help_text='Qué se comunicó de forma clara y efectiva')),
                ('puntos_mejora', models.TextField(help_text='Qué barreras o ruidos se detectaron')),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retroalimentaciones_enviadas', to='dispositivos.dispositivo')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retroalimentaciones_recibidas', to='dispositivos.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='EscuchaActiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_confirmacion', models.DateTimeField(auto_now_add=True)),
                ('dispositivo_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.dispositivo')),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acuses_escucha', to='chat.mensajegrupal')),
            ],
            options={
                'verbose_name': 'Confirmación de Escucha Activa',
                'unique_together': {('mensaje', 'dispositivo_receptor')},
            },
        ),
    ]
