# Generated by Django 6.0.6 on 2026-09-11 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalGrupal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Propósito claro del canal')),
                ('tipo_contexto', models.CharField(choices=[('FORMAL', 'Profesional / Trabajo / Proyecto'), ('INFORMAL', 'Social / Amigos / Familia')], default='FORMAL', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConversacionPrivada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('dispositivo_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_iniciados', to='dispositivos.dispositivo')),
                ('dispositivo_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_recibidos', to='dispositivos.dispositivo')),
            ],
            options={
                'unique_together': {('dispositivo_1', 'dispositivo_2')},
            },
        ),
        migrations.CreateModel(
            name='MensajeGrupal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='chat.canalgrupal')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.dispositivo')),
            ],
            options={
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='MensajePrivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='chat.conversacionprivada')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.dispositivo')),
            ],
            options={
                'ordering': ['fecha_envio'],
            },
        ),
    ]
