# Generated by Django 6.0.6 on 2026-09-11 07:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_dispositivo', models.CharField(default=uuid.uuid4, editable=False, help_text='Token unívoco asignado mediante cookie al dispositivo/navegador', max_length=64, unique=True)),
                ('nombre_asignado', models.CharField(help_text="Nombre identificativo del equipo (Ej. 'Laptop Omar', 'PC Oficina 2')", max_length=100)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dispositivo Local',
                'verbose_name_plural': 'Dispositivos Locales',
                'ordering': ['-ultimo_acceso'],
            },
        ),
    ]
